### PR TITLE
Show opponent name

### PR DESCRIPTION
**Pull request by JKAnderson409**
Added a new field to Match because spaghetti

### CODE REVIEW

**Comment by JKAnderson409** [comment]
Closes #342

**Comment by parkermuir** [comment]
I'm getting an error trying to render this:

Cannot read property 'fullName' of null

**Comment by JKAnderson409** [comment]
That's because we are not saving the Google displayName or any other google data, not even their email address.

**Comment by parkermuir** [comment]
Ok, I'll fix that first with #356

**Comment by parkermuir** [comment]
fixed merge conflict

**Pull request merged**
