### PR TITLE
Decline Mutation and Challenge Modal refactor

### LINKED ISSUE #310: Decline Challenge button in ChallengeModal needs to work with a mutation

### PR DESCRIPTION
**Pull request by parkermuir**
closes #310

### CODE REVIEW

**Comment by parkermuir** [comment]
fixes #313

**Comment by parkermuir** [comment]
closes #318

**Comment by JKAnderson409** [comment]
Throws an error because of mismatch in database. "Louis Pasteur Park", for example, exists on our map but not in the database of courts. When the client tries to render court data it crashes.

**Comment by parkermuir** [comment]
Reset the Matches table in database which should fix this error

**Pull request merged**
